"""Add TicketAttachment model

Revision ID: 4bb82d0a832c
Revises: g6e7f4d3c0b1a
Create Date: 2026-01-05 20:36:21.469077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bb82d0a832c'
down_revision: Union[str, Sequence[str], None] = 'g6e7f4d3c0b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único del adjunto'),
    sa.Column('ticket_id', sa.Integer(), nullable=False, comment='FK a ticket'),
    sa.Column('uploader_id', sa.Integer(), nullable=True, comment='Usuario que subió el archivo'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Nombre original del archivo'),
    sa.Column('filepath', sa.String(length=512), nullable=False, comment='Ruta relativa: tickets/{ticket_id}/{uuid}_{filename}'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME type del archivo (ej: image/jpeg, application/pdf)'),
    sa.Column('size', sa.Integer(), nullable=False, comment='Tamaño en bytes'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_v2.id'], name='fk_ticket_attachments_ticket_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='fk_ticket_attachments_uploader_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_attachments'))
    )
    op.create_index(op.f('ix_ticket_attachments_filepath'), 'ticket_attachments', ['filepath'], unique=True)
    op.create_index(op.f('ix_ticket_attachments_id'), 'ticket_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_ticket_id'), 'ticket_attachments', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_uploader_id'), 'ticket_attachments', ['uploader_id'], unique=False)
    op.alter_column('tickets_v2', 'status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'pending', 'pending_infra', 'resolved', 'closed', name='ticket_status_enum'),
               type_=sa.Enum('open', 'in_progress', 'pending', 'pending_infra', 'resolved', 'closed', name='ticket_status_enum', native_enum=False),
               comment='Estado actual del ticket: open, in_progress, pending, pending_infra, resolved, closed',
               existing_comment='Estado actual del ticket: open, pending, resolved, closed',
               existing_nullable=False)
    op.alter_column('work_orders', 'ot_type',
               existing_type=postgresql.ENUM('repair', 'install', 'pickup', 'infrastructure', name='work_order_type_enum'),
               type_=sa.Enum('repair', 'install', 'pickup', 'infrastructure', name='work_order_type_enum', native_enum=False),
               existing_comment='Tipo de trabajo: repair, install, pickup',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_attachments_uploader_id'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_ticket_id'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_id'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_filepath'), table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    # ### end Alembic commands ###
