"""Add tags system to tickets

Revision ID: 60b46d4e1e39
Revises: 4bb82d0a832c
Create Date: 2026-01-05 21:48:42.716397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60b46d4e1e39'
down_revision: Union[str, Sequence[str], None] = '4bb82d0a832c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único de la etiqueta'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre único de la etiqueta (ej: "Fibra Cortada")'),
    sa.Column('color', sa.String(length=20), nullable=False, comment='Color Hex o nombre Tailwind (ej: "#ef4444" o "emerald")'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Etiqueta activa (visible en UI)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_is_active'), 'tags', ['is_active'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.Integer(), nullable=False, comment='FK a ticket'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='FK a tag'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_ticket_tags_tag_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_v2.id'], name='fk_ticket_tags_ticket_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id', name=op.f('pk_ticket_tags')),
    comment='Asociación Many-to-Many entre tickets y etiquetas'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_is_active'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
