"""crear_tablas_tickets_work_orders

Revision ID: 8bc58d283e34
Revises: 324f44f48d0a
Create Date: 2026-01-02 17:27:54.082289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bc58d283e34'
down_revision: Union[str, Sequence[str], None] = '324f44f48d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key_audit'))
    )
    op.create_index(op.f('ix_api_key_audit_api_key_id'), 'api_key_audit', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_key_audit_timestamp'), 'api_key_audit', ['timestamp'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('rotation_count', sa.Integer(), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_active'), 'api_keys', ['active'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_name'), 'api_keys', ['name'], unique=False)
    op.create_table('tickets_v2',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único del ticket'),
    sa.Column('connection_id', sa.Integer(), nullable=True, comment='FK soft a tabla de conexiones (sin constraint para flexibilidad)'),
    sa.Column('subject', sa.String(length=255), nullable=False, comment='Asunto/Título del ticket'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción detallada del problema'),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'RESOLVED', 'CLOSED', name='ticket_status_enum', native_enum=False), nullable=False, comment='Estado actual del ticket: open, pending, resolved, closed'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority_enum', native_enum=False), nullable=False, comment='Prioridad del incidente: critical, high, medium, low'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='Usuario que creó el ticket'),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True, comment='Operador asignado al ticket'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name='fk_tickets_assigned_to_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='fk_tickets_creator_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets_v2'))
    )
    op.create_index('ix_tickets_assigned', 'tickets_v2', ['assigned_to_id'], unique=False)
    op.create_index('ix_tickets_creator', 'tickets_v2', ['creator_id'], unique=False)
    op.create_index('ix_tickets_status_priority', 'tickets_v2', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_tickets_v2_assigned_to_id'), 'tickets_v2', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tickets_v2_connection_id'), 'tickets_v2', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tickets_v2_creator_id'), 'tickets_v2', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tickets_v2_id'), 'tickets_v2', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_v2_priority'), 'tickets_v2', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_v2_status'), 'tickets_v2', ['status'], unique=False)
    op.create_table('ticket_timeline',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único del evento'),
    sa.Column('ticket_id', sa.Integer(), nullable=False, comment='FK a ticket'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='Usuario que generó el evento (nullable para eventos del sistema)'),
    sa.Column('event_type', sa.Enum('NOTE', 'ALERT', 'OT_EVENT', 'STATUS_CHANGE', name='ticket_timeline_event_type_enum', native_enum=False), nullable=False, comment='Tipo de evento: note, alert, ot_event, status_change'),
    sa.Column('content', sa.Text(), nullable=False, comment='Texto del evento (nota, descripción alerta, etc)'),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON con snapshot técnico: señal ONU, infraestructura, cambios de estado, etc'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='fk_ticket_timeline_author_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_v2.id'], name='fk_ticket_timeline_ticket_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_timeline'))
    )
    op.create_index(op.f('ix_ticket_timeline_author_id'), 'ticket_timeline', ['author_id'], unique=False)
    op.create_index('ix_ticket_timeline_event_type', 'ticket_timeline', ['event_type'], unique=False)
    op.create_index(op.f('ix_ticket_timeline_id'), 'ticket_timeline', ['id'], unique=False)
    op.create_index('ix_ticket_timeline_ticket_created', 'ticket_timeline', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ticket_timeline_ticket_id'), 'ticket_timeline', ['ticket_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único de la OT'),
    sa.Column('ticket_id', sa.Integer(), nullable=False, comment='FK a ticket origen'),
    sa.Column('technician_id', sa.Integer(), nullable=True, comment='Técnico asignado (nullable hasta que planificador asigne)'),
    sa.Column('ot_type', sa.Enum('REPAIR', 'INSTALL', 'PICKUP', name='work_order_type_enum', native_enum=False), nullable=False, comment='Tipo de trabajo: repair, install, pickup'),
    sa.Column('status', sa.Enum('PENDING_PLANNING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='work_order_status_enum', native_enum=False), nullable=False, comment='Estado actual: pending_planning, assigned, in_progress, completed, failed'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha/hora programada para la visita'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha/hora de finalización'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas del técnico sobre el trabajo realizado'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name='fk_work_orders_technician_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_v2.id'], name='fk_work_orders_ticket_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders'))
    )
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index('ix_work_orders_scheduled', 'work_orders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_work_orders_scheduled_at'), 'work_orders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index('ix_work_orders_technician', 'work_orders', ['technician_id'], unique=False)
    op.create_index(op.f('ix_work_orders_technician_id'), 'work_orders', ['technician_id'], unique=False)
    op.create_index(op.f('ix_work_orders_ticket_id'), 'work_orders', ['ticket_id'], unique=False)
    op.create_index('ix_work_orders_ticket_status', 'work_orders', ['ticket_id', 'status'], unique=False)
    op.create_table('work_order_items',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único del item'),
    sa.Column('work_order_id', sa.Integer(), nullable=False, comment='FK a work_order'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='ID del producto en inventario (soft FK, sin constraint)'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='Cantidad utilizada (ej: 40.5 metros de fibra, 1.0 unidad de ONU)'),
    sa.Column('serial_number', sa.String(length=255), nullable=True, comment='Número de serie (para ONUs, Routers, módulos, etc). Formato: TYPE-SN-XXXX'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Observaciones sobre este material'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name='fk_work_order_items_work_order_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_items'))
    )
    op.create_index(op.f('ix_work_order_items_id'), 'work_order_items', ['id'], unique=False)
    op.create_index('ix_work_order_items_product', 'work_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_work_order_items_product_id'), 'work_order_items', ['product_id'], unique=False)
    op.create_index('ix_work_order_items_serial', 'work_order_items', ['serial_number'], unique=False)
    op.create_index(op.f('ix_work_order_items_serial_number'), 'work_order_items', ['serial_number'], unique=False)
    op.create_index(op.f('ix_work_order_items_work_order_id'), 'work_order_items', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_items_work_order_id'), table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_serial_number'), table_name='work_order_items')
    op.drop_index('ix_work_order_items_serial', table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_product_id'), table_name='work_order_items')
    op.drop_index('ix_work_order_items_product', table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_id'), table_name='work_order_items')
    op.drop_table('work_order_items')
    op.drop_index('ix_work_orders_ticket_status', table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_ticket_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_technician_id'), table_name='work_orders')
    op.drop_index('ix_work_orders_technician', table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_scheduled_at'), table_name='work_orders')
    op.drop_index('ix_work_orders_scheduled', table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_ticket_timeline_ticket_id'), table_name='ticket_timeline')
    op.drop_index('ix_ticket_timeline_ticket_created', table_name='ticket_timeline')
    op.drop_index(op.f('ix_ticket_timeline_id'), table_name='ticket_timeline')
    op.drop_index('ix_ticket_timeline_event_type', table_name='ticket_timeline')
    op.drop_index(op.f('ix_ticket_timeline_author_id'), table_name='ticket_timeline')
    op.drop_table('ticket_timeline')
    op.drop_index(op.f('ix_tickets_v2_status'), table_name='tickets_v2')
    op.drop_index(op.f('ix_tickets_v2_priority'), table_name='tickets_v2')
    op.drop_index(op.f('ix_tickets_v2_id'), table_name='tickets_v2')
    op.drop_index(op.f('ix_tickets_v2_creator_id'), table_name='tickets_v2')
    op.drop_index(op.f('ix_tickets_v2_connection_id'), table_name='tickets_v2')
    op.drop_index(op.f('ix_tickets_v2_assigned_to_id'), table_name='tickets_v2')
    op.drop_index('ix_tickets_status_priority', table_name='tickets_v2')
    op.drop_index('ix_tickets_creator', table_name='tickets_v2')
    op.drop_index('ix_tickets_assigned', table_name='tickets_v2')
    op.drop_table('tickets_v2')
    op.drop_index(op.f('ix_api_keys_name'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_active'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_api_key_audit_timestamp'), table_name='api_key_audit')
    op.drop_index(op.f('ix_api_key_audit_api_key_id'), table_name='api_key_audit')
    op.drop_table('api_key_audit')
    # ### end Alembic commands ###
