"""add_audit_logs_universal_motor

Revision ID: a6170cb2f62b
Revises: 2026_03_04_001
Create Date: 2026-03-09 21:04:23.958332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6170cb2f62b'
down_revision: Union[str, Sequence[str], None] = '2026_03_04_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_events_event_type'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_id'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_ticket_id'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_user_id'), table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index(op.f('ix_tickets_assigned_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_category_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_creator_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_legacy_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets_legacy')
    op.drop_table('tickets_legacy')
    # Add entity_name column with default value first to avoid NOT NULL constraint violation
    op.add_column('audit_logs', sa.Column('entity_name', sa.String(length=100), nullable=True, comment='Nombre de la entidad afectada (warehouses, tickets, users, etc.)'))
    # Set default value for existing records
    op.execute('UPDATE audit_logs SET entity_name = COALESCE(entity_type, \'unknown\') WHERE entity_name IS NULL')
    # Make the column NOT NULL after setting values
    op.alter_column('audit_logs', 'entity_name', existing_type=sa.String(length=100), nullable=False)
    op.add_column('audit_logs', sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Valores anteriores del registro (antes de la mutación)'))
    op.add_column('audit_logs', sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Valores nuevos del registro (después de la mutación)'))
    # Create the audit_action_enum type before using it
    op.execute('CREATE TYPE audit_action_enum AS ENUM (\'CREATE\', \'UPDATE\', \'DELETE\', \'LOGIN\', \'LOGOUT\', \'ACCESS_DENIED\', \'EXPORT\', \'IMPORT\')')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID del usuario que ejecutó la acción (NULL para acciones del sistema)',
               existing_nullable=True)
    # Convert action column from VARCHAR to ENUM using explicit USING clause
    op.execute('ALTER TABLE audit_logs ALTER COLUMN action TYPE audit_action_enum USING CASE WHEN action IN (\'CREATE\', \'UPDATE\', \'DELETE\', \'LOGIN\', \'LOGOUT\', \'ACCESS_DENIED\', \'EXPORT\', \'IMPORT\') THEN action::audit_action_enum ELSE \'CREATE\'::audit_action_enum END')
    op.alter_column('audit_logs', 'action',
               existing_nullable=False,
               comment='Tipo de acción ejecutada (CREATE, UPDATE, DELETE, etc.)')
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.INTEGER(),
               comment='ID del registro afectado en la tabla de la entidad',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Dirección IP del cliente (IPv4/IPv6)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment='User-Agent del navegador/cliente',
               existing_nullable=True)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Estado de la operación (success, failure)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'error_message',
               existing_type=sa.VARCHAR(length=500),
               comment='Mensaje de error si la operación falló',
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.drop_constraint(op.f('fk_audit_logs_user_id_users'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_user_id_users'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'details')
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.alter_column('contact_attempts', 'result',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('no_answer', 'busy', 'wrong_number', 'voicemail', 'successful', 'rescheduled', 'refused', name='contact_attempt_result_enum'),
               existing_comment='Resultado del intento de contacto',
               existing_nullable=False)
    op.alter_column('contact_attempts', 'notes',
               existing_type=sa.TEXT(),
               comment="Notas adicionales del coordinador (ej: 'Pide llamar después de las 14hs')",
               existing_comment='Notas adicionales del coordinador',
               existing_nullable=True)
    op.alter_column('contact_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='Timestamp del intento',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'contact_attempts',
        existing_comment='Registro de intentos de contacto telefónico con clientes',
        schema=None
    )
    op.create_index(op.f('ix_engineering_task_timeline_author_id'), 'engineering_task_timeline', ['author_id'], unique=False)
    op.create_index(op.f('ix_engineering_task_timeline_id'), 'engineering_task_timeline', ['id'], unique=False)
    op.alter_column('engineering_tasks', 'task_type',
               existing_type=postgresql.ENUM('incident', 'maintenance', 'project', name='engineering_task_type_enum'),
               type_=sa.Enum('incident', 'maintenance', 'project', name='engineering_task_type_enum', native_enum=False),
               existing_comment='Tipo: incident, maintenance, project',
               existing_nullable=False)
    op.alter_column('engineering_tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='engineering_task_priority_enum'),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='engineering_task_priority_enum', native_enum=False),
               existing_comment='Prioridad: critical, high, medium, low',
               existing_nullable=False)
    op.alter_column('engineering_tasks', 'status',
               existing_type=postgresql.ENUM('backlog', 'in_progress', 'testing', 'completed', 'rejected', name='engineering_task_status_enum'),
               type_=sa.Enum('backlog', 'in_progress', 'testing', 'completed', 'rejected', name='engineering_task_status_enum', native_enum=False),
               existing_comment='Estado: backlog, in_progress, testing, completed, rejected',
               existing_nullable=False)
    op.alter_column('engineering_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de creación del registro',
               existing_comment='Timestamp de creación',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('engineering_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de última actualización',
               existing_comment='Timestamp de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'engineering_tasks',
        existing_comment='Tareas de ingeniería derivadas de tickets o internas',
        schema=None
    )
    op.alter_column('installation_types', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('installation_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('installation_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('installation_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('installation_types_code_key'), 'installation_types', type_='unique')
    op.create_index(op.f('ix_installation_types_code'), 'installation_types', ['code'], unique=True)
    op.create_index(op.f('ix_installation_types_is_active'), 'installation_types', ['is_active'], unique=False)
    op.alter_column('login_attempts', 'username_or_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Username o email usado en el intento de login')
    op.alter_column('login_attempts', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False,
               comment='Dirección IP del intento de login')
    op.alter_column('login_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='True si el login fue exitoso, False si falló')
    op.alter_column('login_attempts', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment='User-Agent del cliente',
               existing_nullable=True)
    op.create_index(op.f('ix_login_attempts_success'), 'login_attempts', ['success'], unique=False)
    op.create_index(op.f('ix_neighborhoods_id'), 'neighborhoods', ['id'], unique=False)
    op.alter_column('products', 'type',
               existing_type=postgresql.ENUM('SERIALIZED', 'BULK', name='product_type_enum'),
               type_=sa.Enum('SERIALIZED', 'BULK', name='product_type_enum', native_enum=False),
               comment='SERIALIZED: equipos con serial único, BULK: materiales a granel',
               existing_comment='SERIALIZED: equipos con serial único, BULK: materiales a granel (metros, unidades sin serial)',
               existing_nullable=False)
    op.alter_column('products', 'min_stock_alert',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Cantidad mínima antes de alertar',
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('serial_items', 'status',
               existing_type=postgresql.ENUM('NEW', 'USED', 'DAMAGED', 'INSTALLED', name='serial_item_status_enum'),
               type_=sa.Enum('NEW', 'USED', 'DAMAGED', 'INSTALLED', name='serial_item_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'NEW'::serial_item_status_enum"))
    op.drop_constraint(op.f('serial_items_serial_number_key'), 'serial_items', type_='unique')
    op.create_index(op.f('ix_serial_items_id'), 'serial_items', ['id'], unique=False)
    op.create_index(op.f('ix_stock_bulk_id'), 'stock_bulk', ['id'], unique=False)
    op.alter_column('stock_movements', 'movement_type',
               existing_type=postgresql.ENUM('PURCHASE', 'TRANSFER', 'CONSUMPTION', 'RECOVERY', 'ADJUSTMENT', name='movement_type_enum'),
               type_=sa.Enum('PURCHASE', 'TRANSFER', 'CONSUMPTION', 'RECOVERY', 'ADJUSTMENT', name='movement_type_enum', native_enum=False),
               comment='PURCHASE: compra/ingreso, TRANSFER: traspaso, CONSUMPTION: uso en OT, RECOVERY: recupero, ADJUSTMENT: ajuste',
               existing_comment='PURCHASE: compra/ingreso, TRANSFER: traspaso, CONSUMPTION: uso en OT, RECOVERY: recupero de campo, ADJUSTMENT: ajuste de inventario',
               existing_nullable=False)
    op.alter_column('stock_movements', 'reference',
               existing_type=sa.VARCHAR(length=200),
               comment="Ej: 'OT #123', 'Remito #50', 'Ajuste manual'",
               existing_comment='Ej: "OT #123", "Remito #50", "Ajuste manual"',
               existing_nullable=True)
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    op.alter_column('team_members', 'id',
               existing_type=sa.INTEGER(),
               comment='ID único del miembro de cuadrilla',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('team_members', 'team_id',
               existing_type=sa.INTEGER(),
               comment='FK a teams',
               existing_nullable=False)
    op.alter_column('team_members', 'user_id',
               existing_type=sa.INTEGER(),
               comment='FK a users',
               existing_nullable=False)
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('leader', 'technician', name='team_role_enum'),
               type_=sa.Enum('leader', 'technician', name='team_role_enum', native_enum=False),
               comment='Rol dentro de la cuadrilla (leader, technician)',
               existing_nullable=False,
               existing_server_default=sa.text("'technician'::team_role_enum"))
    op.alter_column('team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de creación',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.alter_column('teams', 'id',
               existing_type=sa.INTEGER(),
               comment='ID único de la cuadrilla',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment="Nombre único de la cuadrilla (ej: 'Móvil 01 - Norte')",
               existing_nullable=False)
    op.alter_column('teams', 'vehicle_id',
               existing_type=sa.INTEGER(),
               comment='FK a vehicles (reemplaza viejo soft reference)',
               existing_nullable=True)
    op.alter_column('teams', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Cuadrilla activa o archivada',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de creación',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_teams_name'), 'teams', type_='unique')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.alter_column('ticket_categories', 'priority_default',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='ticket_priority_enum', native_enum=False),
               comment='Prioridad sugerida por defecto para esta categoría',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('ticket_reasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de creación del registro',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ticket_reasons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tickets', 'availability_note',
               existing_type=sa.TEXT(),
               comment="Nota sobre disponibilidad horaria del cliente (ej: 'Solo mañanas')",
               existing_nullable=True)
    op.alter_column('tickets', 'connection_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Datos de contacto del cliente: {phone, client_name, client_dni, address, city, ...}',
               existing_nullable=True)
    op.alter_column('tickets', 'category_id',
               existing_type=sa.INTEGER(),
               comment='Categoría del ticket (clasificación funcional)',
               existing_nullable=True)
    op.alter_column('tickets', 'ticket_reason_id',
               existing_type=sa.INTEGER(),
               comment="Motivo específico del ticket (ej: 'Sin Servicio', 'Mudanza')",
               existing_nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.Enum('open', 'in_progress', 'pending', 'pending_infra', 'waiting_internal', 'attention_required', 'resolved', 'closed', name='ticket_status_enum', native_enum=False),
               existing_comment='Estado actual del ticket: open, in_progress, pending, pending_infra, resolved, closed',
               existing_nullable=False)
    op.alter_column('tickets', 'ticket_type',
               existing_type=postgresql.ENUM('technical', 'installation', 'withdrawal', 'relocation', 'administrative', name='ticket_type_enum'),
               type_=sa.Enum('technical', 'installation', 'withdrawal', 'relocation', 'administrative', name='ticket_type_enum', native_enum=False),
               existing_comment='Tipo de flujo: technical, installation, withdrawal, relocation, administrative',
               existing_nullable=False,
               existing_server_default=sa.text("'technical'::ticket_type_enum"))
    op.alter_column('tickets', 'administrative_subtype',
               existing_type=postgresql.ENUM('billing', 'data_update', 'plan_change', 'other', name='administrative_subtype_enum'),
               type_=sa.Enum('billing', 'data_update', 'plan_change', 'other', name='administrative_subtype_enum', native_enum=False),
               existing_comment='Subtipo para tickets administrativos: billing, data_update, plan_change, other',
               existing_nullable=True)
    op.drop_index(op.f('ix_tickets_v2_creator_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_v2_priority'), table_name='tickets')
    op.create_index(op.f('ix_tickets_category_id'), 'tickets', ['category_id'], unique=False)
    op.create_index(op.f('ix_tickets_creator_id'), 'tickets', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tickets_destination_connection_id'), 'tickets', ['destination_connection_id'], unique=False)
    op.create_index(op.f('ix_tickets_origin_connection_id'), 'tickets', ['origin_connection_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Último login exitoso del usuario',
               existing_nullable=True)
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.alter_column('vehicles', 'id',
               existing_type=sa.INTEGER(),
               comment='ID único del vehículo',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('vehicles_id_seq'::regclass)"))
    op.alter_column('vehicles', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment="Nombre descriptivo (ej: 'Móvil 01 - Zona Norte')",
               existing_comment='Nombre descriptivo del vehículo',
               existing_nullable=False)
    op.alter_column('vehicles', 'license_plate',
               existing_type=sa.VARCHAR(length=20),
               comment='Patente del vehículo (ej: AB123CD)',
               existing_comment='Patente del vehículo',
               existing_nullable=True)
    op.alter_column('vehicles', 'vehicle_brand',
               existing_type=sa.VARCHAR(length=50),
               comment='Marca del vehículo (ej: Toyota, Fiat)',
               existing_comment='Marca (ej: Ford, Chevrolet)',
               existing_nullable=True)
    op.alter_column('vehicles', 'vehicle_model',
               existing_type=sa.VARCHAR(length=50),
               comment='Modelo del vehículo (ej: Hilux, Ducato)',
               existing_comment='Modelo (ej: Ranger, S10)',
               existing_nullable=True)
    op.alter_column('vehicles', 'warehouse_id',
               existing_type=sa.INTEGER(),
               comment='FK a warehouse tipo MOBILE (almacén de inventario del vehículo)',
               existing_comment='FK al warehouse (tipo MOBILE) asociado',
               existing_nullable=False)
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'MAINTENANCE', 'RETIRED', 'DONATED', name='vehicle_status_enum'),
               type_=sa.String(length=20),
               existing_comment='Estado operativo del vehículo',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::vehicle_status_enum"))
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de creación',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_name'), 'vehicles', ['name'], unique=False)
    op.alter_column('warehouses', 'type',
               existing_type=postgresql.ENUM('CENTRAL', 'MOBILE', 'VIRTUAL', name='warehouse_type_enum'),
               type_=sa.Enum('CENTRAL', 'MOBILE', 'VIRTUAL', name='warehouse_type_enum', native_enum=False),
               existing_comment='CENTRAL: depósito principal, MOBILE: camioneta de técnico, VIRTUAL: bajas/perdidos/clientes',
               existing_nullable=False)
    op.alter_column('warehouses', 'user_id',
               existing_type=sa.INTEGER(),
               comment='[DEPRECATED] Usar Team + Vehicle en su lugar',
               existing_comment='FK a usuario si es tipo MOBILE (técnico asignado)',
               existing_nullable=True)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.alter_column('work_orders', 'technician_id',
               existing_type=sa.INTEGER(),
               comment='Técnico asignado individual (deprecated, usar team_id)',
               existing_comment='Técnico asignado (nullable hasta que planificador asigne)',
               existing_nullable=True)
    op.alter_column('work_orders', 'team_id',
               existing_type=sa.INTEGER(),
               comment='Cuadrilla asignada para esta OT (NULL si asignación individual legacy)',
               existing_comment='Cuadrilla asignada para esta OT (NULL si asignación individual)',
               existing_nullable=True)
    op.alter_column('work_orders', 'status',
               existing_type=postgresql.ENUM('pending_planning', 'coordinated', 'scheduled', 'assigned', 'in_progress', 'completed', 'failed', 'pending_closure', name='work_order_status_enum'),
               type_=sa.Enum('pending_planning', 'coordinated', 'scheduled', 'assigned', 'in_progress', 'pending_closure', 'completed', 'failed', name='work_order_status_enum', native_enum=False),
               existing_comment='Estado actual: pending_planning, assigned, in_progress, completed, failed',
               existing_nullable=False)
    op.alter_column('work_orders', 'priority',
               existing_type=sa.VARCHAR(length=8),
               comment='Prioridad de la OT: critical, high, medium, low (heredada del ticket padre)',
               existing_comment='Prioridad de la OT (heredada del ticket, pero modificable independientemente)',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('work_orders', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha/hora programada para la visita (deprecated, usar scheduled_start)',
               existing_comment='Fecha/hora programada para la visita',
               existing_nullable=True)
    op.alter_column('work_orders', 'photo_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array de URLs de fotos de evidencia de la resolución',
               existing_comment='URLs de fotos de la resolución (instalaciones/reparaciones) - array de strings',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('work_orders', 'custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Datos flexibles del técnico (JSONB): \n        - optical_signal_dbm: float (nivel de luz)\n        - speedtest_download_mbps: float\n        - speedtest_upload_mbps: float\n        - mac_address_recovered: str (para bajas)\n        - onu_serial_installed: str (para instalaciones)\n        - beholder_check_result: dict (diagnóstico rápido)\n        - photos: list[str] (URLs de fotos)\n        ',
               existing_comment='Datos flexibles del técnico (JSONB): optical_signal_dbm, speedtest, photos, etc.',
               existing_nullable=True)
    op.drop_index(op.f('ix_work_orders_pending_closure'), table_name='work_orders', postgresql_where="(status = 'pending_closure'::work_order_status_enum)")
    op.drop_index(op.f('ix_work_orders_pending_closure_by_tech'), table_name='work_orders', postgresql_where="(status = 'pending_closure'::work_order_status_enum)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_work_orders_pending_closure_by_tech'), 'work_orders', ['status', 'technician_id'], unique=False, postgresql_where="(status = 'pending_closure'::work_order_status_enum)")
    op.create_index(op.f('ix_work_orders_pending_closure'), 'work_orders', ['status', 'team_id', 'scheduled_end'], unique=False, postgresql_where="(status = 'pending_closure'::work_order_status_enum)")
    op.alter_column('work_orders', 'custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Datos flexibles del técnico (JSONB): optical_signal_dbm, speedtest, photos, etc.',
               existing_comment='Datos flexibles del técnico (JSONB): \n        - optical_signal_dbm: float (nivel de luz)\n        - speedtest_download_mbps: float\n        - speedtest_upload_mbps: float\n        - mac_address_recovered: str (para bajas)\n        - onu_serial_installed: str (para instalaciones)\n        - beholder_check_result: dict (diagnóstico rápido)\n        - photos: list[str] (URLs de fotos)\n        ',
               existing_nullable=True)
    op.alter_column('work_orders', 'photo_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='URLs de fotos de la resolución (instalaciones/reparaciones) - array de strings',
               existing_comment='Array de URLs de fotos de evidencia de la resolución',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('work_orders', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha/hora programada para la visita',
               existing_comment='Fecha/hora programada para la visita (deprecated, usar scheduled_start)',
               existing_nullable=True)
    op.alter_column('work_orders', 'priority',
               existing_type=sa.VARCHAR(length=8),
               comment='Prioridad de la OT (heredada del ticket, pero modificable independientemente)',
               existing_comment='Prioridad de la OT: critical, high, medium, low (heredada del ticket padre)',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('work_orders', 'status',
               existing_type=sa.Enum('pending_planning', 'coordinated', 'scheduled', 'assigned', 'in_progress', 'pending_closure', 'completed', 'failed', name='work_order_status_enum', native_enum=False),
               type_=postgresql.ENUM('pending_planning', 'coordinated', 'scheduled', 'assigned', 'in_progress', 'completed', 'failed', 'pending_closure', name='work_order_status_enum'),
               existing_comment='Estado actual: pending_planning, assigned, in_progress, completed, failed',
               existing_nullable=False)
    op.alter_column('work_orders', 'team_id',
               existing_type=sa.INTEGER(),
               comment='Cuadrilla asignada para esta OT (NULL si asignación individual)',
               existing_comment='Cuadrilla asignada para esta OT (NULL si asignación individual legacy)',
               existing_nullable=True)
    op.alter_column('work_orders', 'technician_id',
               existing_type=sa.INTEGER(),
               comment='Técnico asignado (nullable hasta que planificador asigne)',
               existing_comment='Técnico asignado individual (deprecated, usar team_id)',
               existing_nullable=True)
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.alter_column('warehouses', 'user_id',
               existing_type=sa.INTEGER(),
               comment='FK a usuario si es tipo MOBILE (técnico asignado)',
               existing_comment='[DEPRECATED] Usar Team + Vehicle en su lugar',
               existing_nullable=True)
    op.alter_column('warehouses', 'type',
               existing_type=sa.Enum('CENTRAL', 'MOBILE', 'VIRTUAL', name='warehouse_type_enum', native_enum=False),
               type_=postgresql.ENUM('CENTRAL', 'MOBILE', 'VIRTUAL', name='warehouse_type_enum'),
               existing_comment='CENTRAL: depósito principal, MOBILE: camioneta de técnico, VIRTUAL: bajas/perdidos/clientes',
               existing_nullable=False)
    op.drop_index(op.f('ix_vehicles_name'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de creación',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vehicles', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ACTIVE', 'MAINTENANCE', 'RETIRED', 'DONATED', name='vehicle_status_enum'),
               existing_comment='Estado operativo del vehículo',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::vehicle_status_enum"))
    op.alter_column('vehicles', 'warehouse_id',
               existing_type=sa.INTEGER(),
               comment='FK al warehouse (tipo MOBILE) asociado',
               existing_comment='FK a warehouse tipo MOBILE (almacén de inventario del vehículo)',
               existing_nullable=False)
    op.alter_column('vehicles', 'vehicle_model',
               existing_type=sa.VARCHAR(length=50),
               comment='Modelo (ej: Ranger, S10)',
               existing_comment='Modelo del vehículo (ej: Hilux, Ducato)',
               existing_nullable=True)
    op.alter_column('vehicles', 'vehicle_brand',
               existing_type=sa.VARCHAR(length=50),
               comment='Marca (ej: Ford, Chevrolet)',
               existing_comment='Marca del vehículo (ej: Toyota, Fiat)',
               existing_nullable=True)
    op.alter_column('vehicles', 'license_plate',
               existing_type=sa.VARCHAR(length=20),
               comment='Patente del vehículo',
               existing_comment='Patente del vehículo (ej: AB123CD)',
               existing_nullable=True)
    op.alter_column('vehicles', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment='Nombre descriptivo del vehículo',
               existing_comment="Nombre descriptivo (ej: 'Móvil 01 - Zona Norte')",
               existing_nullable=False)
    op.alter_column('vehicles', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único del vehículo',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('vehicles_id_seq'::regclass)"))
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Último login exitoso del usuario',
               existing_nullable=True)
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_origin_connection_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_destination_connection_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_creator_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category_id'), table_name='tickets')
    op.create_index(op.f('ix_tickets_v2_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_v2_creator_id'), 'tickets', ['creator_id'], unique=False)
    op.alter_column('tickets', 'administrative_subtype',
               existing_type=sa.Enum('billing', 'data_update', 'plan_change', 'other', name='administrative_subtype_enum', native_enum=False),
               type_=postgresql.ENUM('billing', 'data_update', 'plan_change', 'other', name='administrative_subtype_enum'),
               existing_comment='Subtipo para tickets administrativos: billing, data_update, plan_change, other',
               existing_nullable=True)
    op.alter_column('tickets', 'ticket_type',
               existing_type=sa.Enum('technical', 'installation', 'withdrawal', 'relocation', 'administrative', name='ticket_type_enum', native_enum=False),
               type_=postgresql.ENUM('technical', 'installation', 'withdrawal', 'relocation', 'administrative', name='ticket_type_enum'),
               existing_comment='Tipo de flujo: technical, installation, withdrawal, relocation, administrative',
               existing_nullable=False,
               existing_server_default=sa.text("'technical'::ticket_type_enum"))
    op.alter_column('tickets', 'status',
               existing_type=sa.Enum('open', 'in_progress', 'pending', 'pending_infra', 'waiting_internal', 'attention_required', 'resolved', 'closed', name='ticket_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=25),
               existing_comment='Estado actual del ticket: open, in_progress, pending, pending_infra, resolved, closed',
               existing_nullable=False)
    op.alter_column('tickets', 'ticket_reason_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Motivo específico del ticket (ej: 'Sin Servicio', 'Mudanza')",
               existing_nullable=True)
    op.alter_column('tickets', 'category_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Categoría del ticket (clasificación funcional)',
               existing_nullable=True)
    op.alter_column('tickets', 'connection_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Datos de contacto del cliente: {phone, client_name, client_dni, address, city, ...}',
               existing_nullable=True)
    op.alter_column('tickets', 'availability_note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Nota sobre disponibilidad horaria del cliente (ej: 'Solo mañanas')",
               existing_nullable=True)
    op.alter_column('ticket_reasons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ticket_reasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de creación del registro',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ticket_categories', 'priority_default',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='ticket_priority_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Prioridad sugerida por defecto para esta categoría',
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=True)
    op.create_unique_constraint(op.f('uq_teams_name'), 'teams', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de creación',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Cuadrilla activa o archivada',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('teams', 'vehicle_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK a vehicles (reemplaza viejo soft reference)',
               existing_nullable=True)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment="Nombre único de la cuadrilla (ej: 'Móvil 01 - Norte')",
               existing_nullable=False)
    op.alter_column('teams', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único de la cuadrilla',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=True)
    op.alter_column('team_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de creación',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'role',
               existing_type=sa.Enum('leader', 'technician', name='team_role_enum', native_enum=False),
               type_=postgresql.ENUM('leader', 'technician', name='team_role_enum'),
               comment=None,
               existing_comment='Rol dentro de la cuadrilla (leader, technician)',
               existing_nullable=False,
               existing_server_default=sa.text("'technician'::team_role_enum"))
    op.alter_column('team_members', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK a users',
               existing_nullable=False)
    op.alter_column('team_members', 'team_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK a teams',
               existing_nullable=False)
    op.alter_column('team_members', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único del miembro de cuadrilla',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_stock_movements_id'), table_name='stock_movements')
    op.alter_column('stock_movements', 'reference',
               existing_type=sa.VARCHAR(length=200),
               comment='Ej: "OT #123", "Remito #50", "Ajuste manual"',
               existing_comment="Ej: 'OT #123', 'Remito #50', 'Ajuste manual'",
               existing_nullable=True)
    op.alter_column('stock_movements', 'movement_type',
               existing_type=sa.Enum('PURCHASE', 'TRANSFER', 'CONSUMPTION', 'RECOVERY', 'ADJUSTMENT', name='movement_type_enum', native_enum=False),
               type_=postgresql.ENUM('PURCHASE', 'TRANSFER', 'CONSUMPTION', 'RECOVERY', 'ADJUSTMENT', name='movement_type_enum'),
               comment='PURCHASE: compra/ingreso, TRANSFER: traspaso, CONSUMPTION: uso en OT, RECOVERY: recupero de campo, ADJUSTMENT: ajuste de inventario',
               existing_comment='PURCHASE: compra/ingreso, TRANSFER: traspaso, CONSUMPTION: uso en OT, RECOVERY: recupero, ADJUSTMENT: ajuste',
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_bulk_id'), table_name='stock_bulk')
    op.drop_index(op.f('ix_serial_items_id'), table_name='serial_items')
    op.create_unique_constraint(op.f('serial_items_serial_number_key'), 'serial_items', ['serial_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('serial_items', 'status',
               existing_type=sa.Enum('NEW', 'USED', 'DAMAGED', 'INSTALLED', name='serial_item_status_enum', native_enum=False),
               type_=postgresql.ENUM('NEW', 'USED', 'DAMAGED', 'INSTALLED', name='serial_item_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'NEW'::serial_item_status_enum"))
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'min_stock_alert',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Cantidad mínima antes de alertar',
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'type',
               existing_type=sa.Enum('SERIALIZED', 'BULK', name='product_type_enum', native_enum=False),
               type_=postgresql.ENUM('SERIALIZED', 'BULK', name='product_type_enum'),
               comment='SERIALIZED: equipos con serial único, BULK: materiales a granel (metros, unidades sin serial)',
               existing_comment='SERIALIZED: equipos con serial único, BULK: materiales a granel',
               existing_nullable=False)
    op.drop_index(op.f('ix_neighborhoods_id'), table_name='neighborhoods')
    op.drop_index(op.f('ix_login_attempts_success'), table_name='login_attempts')
    op.alter_column('login_attempts', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='User-Agent del cliente',
               existing_nullable=True)
    op.alter_column('login_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='True si el login fue exitoso, False si falló')
    op.alter_column('login_attempts', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True,
               comment=None,
               existing_comment='Dirección IP del intento de login')
    op.alter_column('login_attempts', 'username_or_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Username o email usado en el intento de login')
    op.drop_index(op.f('ix_installation_types_is_active'), table_name='installation_types')
    op.drop_index(op.f('ix_installation_types_code'), table_name='installation_types')
    op.create_unique_constraint(op.f('installation_types_code_key'), 'installation_types', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('installation_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('installation_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('installation_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('installation_types', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_table_comment(
        'engineering_tasks',
        'Tareas de ingeniería derivadas de tickets o internas',
        existing_comment=None,
        schema=None
    )
    op.alter_column('engineering_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp de última actualización',
               existing_comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('engineering_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp de creación',
               existing_comment='Fecha de creación del registro',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('engineering_tasks', 'status',
               existing_type=sa.Enum('backlog', 'in_progress', 'testing', 'completed', 'rejected', name='engineering_task_status_enum', native_enum=False),
               type_=postgresql.ENUM('backlog', 'in_progress', 'testing', 'completed', 'rejected', name='engineering_task_status_enum'),
               existing_comment='Estado: backlog, in_progress, testing, completed, rejected',
               existing_nullable=False)
    op.alter_column('engineering_tasks', 'priority',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='engineering_task_priority_enum', native_enum=False),
               type_=postgresql.ENUM('low', 'medium', 'high', 'critical', name='engineering_task_priority_enum'),
               existing_comment='Prioridad: critical, high, medium, low',
               existing_nullable=False)
    op.alter_column('engineering_tasks', 'task_type',
               existing_type=sa.Enum('incident', 'maintenance', 'project', name='engineering_task_type_enum', native_enum=False),
               type_=postgresql.ENUM('incident', 'maintenance', 'project', name='engineering_task_type_enum'),
               existing_comment='Tipo: incident, maintenance, project',
               existing_nullable=False)
    op.drop_index(op.f('ix_engineering_task_timeline_id'), table_name='engineering_task_timeline')
    op.drop_index(op.f('ix_engineering_task_timeline_author_id'), table_name='engineering_task_timeline')
    op.create_table_comment(
        'contact_attempts',
        'Registro de intentos de contacto telefónico con clientes',
        existing_comment=None,
        schema=None
    )
    op.alter_column('contact_attempts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Timestamp del intento',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contact_attempts', 'notes',
               existing_type=sa.TEXT(),
               comment='Notas adicionales del coordinador',
               existing_comment="Notas adicionales del coordinador (ej: 'Pide llamar después de las 14hs')",
               existing_nullable=True)
    op.alter_column('contact_attempts', 'result',
               existing_type=sa.Enum('no_answer', 'busy', 'wrong_number', 'voicemail', 'successful', 'rescheduled', 'refused', name='contact_attempt_result_enum'),
               type_=sa.VARCHAR(length=50),
               existing_comment='Resultado del intento de contacto',
               existing_nullable=False)
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.add_column('audit_logs', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_audit_logs_user_id_users'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_logs_user_id_users'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'error_message',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Mensaje de error si la operación falló',
               existing_nullable=True)
    op.alter_column('audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Estado de la operación (success, failure)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='User-Agent del navegador/cliente',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='Dirección IP del cliente (IPv4/IPv6)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del registro afectado en la tabla de la entidad',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'ACCESS_DENIED', 'EXPORT', 'IMPORT', name='audit_action_enum'),
               type_=sa.VARCHAR(length=100),
               nullable=True,
               comment=None,
               existing_comment='Tipo de acción ejecutada (CREATE, UPDATE, DELETE, etc.)')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del usuario que ejecutó la acción (NULL para acciones del sistema)',
               existing_nullable=True)
    op.drop_column('audit_logs', 'new_values')
    op.drop_column('audit_logs', 'old_values')
    op.drop_column('audit_logs', 'entity_name')
    op.create_table('tickets_legacy',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tickets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority_enum'), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['assigned_id'], ['users.id'], name='fk_tickets_assigned_id_users'),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], name='fk_tickets_category_id_ticket_categories'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='fk_tickets_creator_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_tickets'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tickets_priority'), 'tickets_legacy', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_legacy_id'), 'tickets_legacy', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets_legacy', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tickets_creator_id'), 'tickets_legacy', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tickets_category_id'), 'tickets_legacy', ['category_id'], unique=False)
    op.create_index(op.f('ix_tickets_assigned_id'), 'tickets_legacy', ['assigned_id'], unique=False)
    op.create_table('ticket_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('CREATED', 'COMMENT', 'STATUS_CHANGE', name='ticket_event_type_enum'), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_legacy.id'], name=op.f('fk_ticket_events_ticket_id_tickets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ticket_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_events'))
    )
    op.create_index(op.f('ix_ticket_events_user_id'), 'ticket_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_ticket_events_ticket_id'), 'ticket_events', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_events_id'), 'ticket_events', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_events_event_type'), 'ticket_events', ['event_type'], unique=False)
    # ### end Alembic commands ###
