"""agregar last_login a usuarios

Revision ID: c01629c3b4dc
Revises: fdbc3ada2627
Create Date: 2026-01-09 10:58:10.773296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c01629c3b4dc'
down_revision: Union[str, Sequence[str], None] = 'fdbc3ada2627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_events_event_type'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_id'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_ticket_id'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_user_id'), table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index(op.f('ix_ticket_categories_id'), table_name='ticket_categories')
    op.drop_index(op.f('ix_ticket_categories_name'), table_name='ticket_categories')
    op.drop_table('ticket_categories')
    op.drop_index(op.f('ix_tickets_assigned_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_category_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_creator_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_legacy_id'), table_name='tickets_legacy')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets_legacy')
    op.drop_table('tickets_legacy')
    op.alter_column('tickets', 'availability_note',
               existing_type=sa.TEXT(),
               comment="Nota sobre disponibilidad horaria del cliente (ej: 'Solo mañanas')",
               existing_nullable=True)
    op.alter_column('tickets', 'ticket_type',
               existing_type=postgresql.ENUM('technical', 'installation', 'withdrawal', 'relocation', 'administrative', name='ticket_type_enum'),
               type_=sa.Enum('technical', 'installation', 'withdrawal', 'relocation', 'administrative', name='ticket_type_enum', native_enum=False),
               existing_comment='Tipo de flujo: technical, installation, withdrawal, relocation, administrative',
               existing_nullable=False,
               existing_server_default=sa.text("'technical'::ticket_type_enum"))
    op.alter_column('tickets', 'administrative_subtype',
               existing_type=postgresql.ENUM('billing', 'data_update', 'plan_change', 'other', name='administrative_subtype_enum'),
               type_=sa.Enum('billing', 'data_update', 'plan_change', 'other', name='administrative_subtype_enum', native_enum=False),
               existing_comment='Subtipo para tickets administrativos: billing, data_update, plan_change, other',
               existing_nullable=True)
    op.drop_index(op.f('ix_tickets_v2_creator_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_v2_priority'), table_name='tickets')
    op.create_index(op.f('ix_tickets_creator_id'), 'tickets', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tickets_destination_connection_id'), 'tickets', ['destination_connection_id'], unique=False)
    op.create_index(op.f('ix_tickets_origin_connection_id'), 'tickets', ['origin_connection_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Último login exitoso del usuario'))
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.alter_column('work_orders', 'photo_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Array de URLs de fotos de evidencia de la resolución',
               existing_comment='URLs de fotos de la resolución (instalaciones/reparaciones) - array de strings',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('work_orders', 'custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Datos flexibles del técnico (JSONB): \n        - optical_signal_dbm: float (nivel de luz)\n        - speedtest_download_mbps: float\n        - speedtest_upload_mbps: float\n        - mac_address_recovered: str (para bajas)\n        - onu_serial_installed: str (para instalaciones)\n        - beholder_check_result: dict (diagnóstico rápido)\n        - photos: list[str] (URLs de fotos)\n        ',
               existing_comment='Datos flexibles del técnico (JSONB): optical_signal_dbm, speedtest, photos, etc.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_orders', 'custom_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Datos flexibles del técnico (JSONB): optical_signal_dbm, speedtest, photos, etc.',
               existing_comment='Datos flexibles del técnico (JSONB): \n        - optical_signal_dbm: float (nivel de luz)\n        - speedtest_download_mbps: float\n        - speedtest_upload_mbps: float\n        - mac_address_recovered: str (para bajas)\n        - onu_serial_installed: str (para instalaciones)\n        - beholder_check_result: dict (diagnóstico rápido)\n        - photos: list[str] (URLs de fotos)\n        ',
               existing_nullable=True)
    op.alter_column('work_orders', 'photo_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='URLs de fotos de la resolución (instalaciones/reparaciones) - array de strings',
               existing_comment='Array de URLs de fotos de evidencia de la resolución',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_column('users', 'last_login')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_origin_connection_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_destination_connection_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_creator_id'), table_name='tickets')
    op.create_index(op.f('ix_tickets_v2_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_v2_creator_id'), 'tickets', ['creator_id'], unique=False)
    op.alter_column('tickets', 'administrative_subtype',
               existing_type=sa.Enum('billing', 'data_update', 'plan_change', 'other', name='administrative_subtype_enum', native_enum=False),
               type_=postgresql.ENUM('billing', 'data_update', 'plan_change', 'other', name='administrative_subtype_enum'),
               existing_comment='Subtipo para tickets administrativos: billing, data_update, plan_change, other',
               existing_nullable=True)
    op.alter_column('tickets', 'ticket_type',
               existing_type=sa.Enum('technical', 'installation', 'withdrawal', 'relocation', 'administrative', name='ticket_type_enum', native_enum=False),
               type_=postgresql.ENUM('technical', 'installation', 'withdrawal', 'relocation', 'administrative', name='ticket_type_enum'),
               existing_comment='Tipo de flujo: technical, installation, withdrawal, relocation, administrative',
               existing_nullable=False,
               existing_server_default=sa.text("'technical'::ticket_type_enum"))
    op.alter_column('tickets', 'availability_note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Nota sobre disponibilidad horaria del cliente (ej: 'Solo mañanas')",
               existing_nullable=True)
    op.create_table('tickets_legacy',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tickets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority_enum'), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['assigned_id'], ['users.id'], name='fk_tickets_assigned_id_users'),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], name='fk_tickets_category_id_ticket_categories'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='fk_tickets_creator_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_tickets'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tickets_priority'), 'tickets_legacy', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_legacy_id'), 'tickets_legacy', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets_legacy', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tickets_creator_id'), 'tickets_legacy', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tickets_category_id'), 'tickets_legacy', ['category_id'], unique=False)
    op.create_index(op.f('ix_tickets_assigned_id'), 'tickets_legacy', ['assigned_id'], unique=False)
    op.create_table('ticket_categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ticket_categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id', name='pk_ticket_categories'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_ticket_categories_name'), 'ticket_categories', ['name'], unique=True)
    op.create_index(op.f('ix_ticket_categories_id'), 'ticket_categories', ['id'], unique=False)
    op.create_table('ticket_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('CREATED', 'COMMENT', 'STATUS_CHANGE', name='ticket_event_type_enum'), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_legacy.id'], name=op.f('fk_ticket_events_ticket_id_tickets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ticket_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_events'))
    )
    op.create_index(op.f('ix_ticket_events_user_id'), 'ticket_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_ticket_events_ticket_id'), 'ticket_events', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_events_id'), 'ticket_events', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_events_event_type'), 'ticket_events', ['event_type'], unique=False)
    # ### end Alembic commands ###
