"""
Router de administración de usuarios (v2)

Endpoints protegidos para gestión de usuarios: crear, actualizar, resetear contraseña,
cambiar rol, activar/desactivar. Requiere permisos de administración.
"""
import secrets
import string
import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, status, Request
from sqlalchemy.orm import Session

from src.database import get_db
from src.core.security import require_admin, get_password_hash
from src.repositories.user_repository import UserRepository, RoleRepository
from src.schemas.user_schemas import (
    UserCreate,
    UserUpdate,
    UserResponse,
    PasswordResetRequest,
    PasswordResetResponse,
    RoleChangeRequest,
    StatusUpdateRequest,
)
from src.utils.audit import log_create, log_update, log_delete, get_entity_dict


router = APIRouter(tags=["Users V2"])
logger = logging.getLogger("uvicorn.error")


def _generate_temporary_password(length: int = 14) -> str:
    """Genera una contraseña temporal robusta.

    Reglas: mínimo 1 mayúscula, 1 minúscula, 1 dígito y 1 símbolo.
    """
    if length < 8:
        length = 8
    categories = [
        secrets.choice(string.ascii_uppercase),
        secrets.choice(string.ascii_lowercase),
        secrets.choice(string.digits),
        secrets.choice("!@#$%^&*()-_=+[]{};:,.?/"),
    ]
    pool = string.ascii_letters + string.digits + "!@#$%^&*()-_=+[]{};:,.?/"
    remaining = [secrets.choice(pool) for _ in range(length - len(categories))]
    chars = categories + remaining
    secrets.SystemRandom().shuffle(chars)
    return "".join(chars)


@router.get("/", response_model=list[UserResponse])
def list_users(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
    _admin = Depends(require_admin),
):
    """Lista todos los usuarios del sistema (solo administradores)."""
    user_repo = UserRepository(db)
    users = user_repo.get_all(skip=skip, limit=limit)
    return users


@router.post("/", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
def create_user_admin(
    data: UserCreate,
    request: Request,
    db: Session = Depends(get_db),
    _admin = Depends(require_admin),
):
    """Crea un usuario (solo administradores)."""
    user_repo = UserRepository(db)

    # Unicidad de email/username
    if user_repo.get_by_email(data.email):
        raise HTTPException(status_code=400, detail="Email ya registrado")
    if user_repo.get_by_username(data.username):
        raise HTTPException(status_code=400, detail="Username ya en uso")

    # Hash de password
    hashed = get_password_hash(data.password)

    from src.models.user import User
    user = User(
        email=data.email,
        username=data.username,
        full_name=data.full_name,
        hashed_password=hashed,
        is_active=True,
        is_superuser=False,
        role_id=data.role_id,
    )
    created = user_repo.create(user)

    # 🔒 AUDIT LOG: Registrar creación de usuario
    try:
        log_create(
            db=db,
            user_id=_admin.id,
            entity_name="users",
            entity_id=created.id,
            new_values={"email": created.email, "username": created.username, "role_id": created.role_id}
        )
    except Exception as audit_error:
        logger.error(f"❌ [AUDIT] Error al registrar creación de usuario {created.id}: {audit_error}")

    return created


@router.post("/{user_id}/reset-password", response_model=PasswordResetResponse)
def reset_password_admin(
    user_id: int,
    payload: Optional[PasswordResetRequest] = None,
    request: Request = None,
    db: Session = Depends(get_db),
    current_admin = Depends(require_admin),
):
    """
    Resetea contraseña de un usuario (solo administradores).
    
    Si se proporciona new_password en el payload, se usa esa.
    Si no, se autogenera una contraseña temporal robusta.
    """
    user_repo = UserRepository(db)
    user = user_repo.get(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="Usuario no encontrado")

    if user.id == current_admin.id:
        raise HTTPException(status_code=400, detail="No puedes resetear tu propia contraseña aquí")

    # Usar contraseña proporcionada o generar una
    if payload and payload.new_password:
        temp_password = payload.new_password
    else:
        temp_password = _generate_temporary_password()
    
    user.hashed_password = get_password_hash(temp_password)
    user_repo.update(user)

    # Audit
    try:
        AuditService.log_action(
            db=db,
            user_id=current_admin.id,
            action="user.reset_password",
            entity_type="User",
            entity_id=user.id,
            ip_address=get_client_ip(request),
            status="success",
            details={"method": "custom" if payload and payload.new_password else "autogenerated"},
        )
    except Exception:
        pass

    return PasswordResetResponse(user_id=user.id, temporary_password=temp_password)


@router.patch("/{user_id}/role", response_model=UserResponse)
def change_user_role(
    user_id: int,
    payload: RoleChangeRequest,
    request: Request,
    db: Session = Depends(get_db),
    current_admin = Depends(require_admin),
):
    """Cambia el rol de un usuario (solo administradores)."""
    user_repo = UserRepository(db)
    role_repo = RoleRepository(db)

    user = user_repo.get(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="Usuario no encontrado")

    if user.id == current_admin.id:
        raise HTTPException(status_code=400, detail="No puedes cambiar tu propio rol")

    role = role_repo.get(payload.role_id)
    if not role:
        raise HTTPException(status_code=404, detail="Rol no encontrado")

    # Capturar valor anterior para auditoría
    old_values = {"role_id": user.role_id}
    
    user.role_id = role.id
    updated = user_repo.update(user)

    # 🔒 AUDIT LOG: Registrar cambio de rol
    try:
        log_update(
            db=db,
            user_id=current_admin.id,
            entity_name="users",
            entity_id=user.id,
            old_values=old_values,
            new_values={"role_id": role.id, "role_name": role.name}
        )
    except Exception as audit_error:
        logger.error(f"❌ [AUDIT] Error al registrar cambio de rol de usuario {user.id}: {audit_error}")

    return updated


@router.patch("/{user_id}/status", response_model=UserResponse)
def update_user_status(
    user_id: int,
    payload: StatusUpdateRequest,
    request: Request,
    db: Session = Depends(get_db),
    current_admin = Depends(require_admin),
):
    """Activa o desactiva un usuario (solo administradores)."""
    user_repo = UserRepository(db)
    user = user_repo.get(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="Usuario no encontrado")

    if user.id == current_admin.id:
        raise HTTPException(status_code=400, detail="No puedes cambiar tu propio estado")

    # Capturar valor anterior para auditoría
    old_values = {"is_active": user.is_active}
    
    user.is_active = bool(payload.is_active)
    updated = user_repo.update(user)

    # 🔒 AUDIT LOG: Registrar cambio de estado
    try:
        log_update(
            db=db,
            user_id=current_admin.id,
            entity_name="users",
            entity_id=user.id,
            old_values=old_values,
            new_values={"is_active": updated.is_active}
        )
    except Exception as audit_error:
        logger.error(f"❌ [AUDIT] Error al registrar cambio de estado de usuario {user.id}: {audit_error}")

    return updated


@router.patch("/{user_id}", response_model=UserResponse)
def update_user(
    user_id: int,
    data: UserUpdate,
    request: Request,
    db: Session = Depends(get_db),
    current_admin = Depends(require_admin),
):
    """
    Actualiza los datos de un usuario (solo administradores).

    Permite modificar: email, username, full_name, role_id, is_active, is_superuser.
    No permite cambiar la contraseña (usar reset-password para eso).
    """
    user_repo = UserRepository(db)
    user = user_repo.get(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="Usuario no encontrado")

    # No permitir que un admin se modifique a sí mismo el rol o superuser
    if user.id == current_admin.id:
        if data.role_id is not None or data.is_superuser is not None:
            raise HTTPException(
                status_code=400,
                detail="No puedes modificar tu propio rol o permisos de superusuario"
            )

    # Verificar unicidad de email si cambió
    if data.email is not None and data.email != user.email:
        if user_repo.get_by_email(data.email):
            raise HTTPException(status_code=400, detail="Email ya registrado")
        user.email = data.email

    # Verificar unicidad de username si cambió
    if data.username is not None and data.username != user.username:
        if user_repo.get_by_username(data.username):
            raise HTTPException(status_code=400, detail="Username ya en uso")
        user.username = data.username

    # Capturar valores anteriores para auditoría
    old_values = get_entity_dict(user)

    if data.full_name is not None:
        user.full_name = data.full_name
    if data.is_active is not None:
        user.is_active = data.is_active
    if data.is_superuser is not None:
        user.is_superuser = data.is_superuser
    if data.role_id is not None:
        role_repo = RoleRepository(db)
        role = role_repo.get(data.role_id)
        if not role:
            raise HTTPException(status_code=404, detail="Rol no encontrado")
        user.role_id = role.id

    updated = user_repo.update(user)

    # 🔒 AUDIT LOG: Registrar actualización de usuario
    try:
        log_update(
            db=db,
            user_id=current_admin.id,
            entity_name="users",
            entity_id=user.id,
            old_values=old_values,
            new_values=get_entity_dict(updated)
        )
    except Exception as audit_error:
        logger.error(f"❌ [AUDIT] Error al registrar actualización de usuario {user.id}: {audit_error}")

    return updated


@router.delete("/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_user_permanently(
    user_id: int,
    request: Request,
    db: Session = Depends(get_db),
    current_admin = Depends(require_admin),
):
    """
    Elimina permanentemente un usuario (solo administradores).
    
    SOLO permite eliminar usuarios SIN datos históricos:
    - Sin membresías en equipos (team_memberships)
    - Sin acciones de auditoría
    - Sin último login (nunca usó el sistema)
    
    Para usuarios con historial, usar PATCH /status (desactivar).
    """
    user_repo = UserRepository(db)
    user = user_repo.get(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="Usuario no encontrado")

    if user.id == current_admin.id:
        raise HTTPException(
            status_code=400, 
            detail="No puedes eliminar tu propia cuenta"
        )

    # Verificar que el usuario no tenga datos históricos
    validation_errors = []

    # 1. Team memberships
    if user.team_memberships and len(user.team_memberships) > 0:
        validation_errors.append(
            f"tiene {len(user.team_memberships)} asignación(es) en equipos"
        )

    # 2. Último login (si usó el sistema)
    if user.last_login is not None:
        validation_errors.append("ya inició sesión en el sistema")

    # 3. Auditoría (si ejecutó acciones)
    try:
        from src.models.audit import AuditLog
        audit_count = db.query(AuditLog).filter(AuditLog.user_id == user_id).count()
        if audit_count > 0:
            validation_errors.append(f"tiene {audit_count} acción(es) registrada(s)")
    except Exception:
        # Si no existe tabla de auditoría, continuar
        pass

    # Si tiene datos, rechazar eliminación
    if validation_errors:
        raise HTTPException(
            status_code=400,
            detail={
                "message": "No se puede eliminar: usuario con datos históricos",
                "reasons": validation_errors,
                "suggestion": "Usar PATCH /status para desactivar en lugar de eliminar"
            }
        )

    # Si no tiene datos, proceder con eliminación
    old_values = {"username": user.username, "email": user.email, "role_id": user.role_id}
    user_id_for_audit = user.id
    username = user.username
    email = user.email
    
    user_repo.delete(user_id)

    # 🔒 AUDIT LOG: Registrar eliminación de usuario
    try:
        log_delete(
            db=db,
            user_id=current_admin.id,
            entity_name="users",
            entity_id=user_id_for_audit,
            old_values=old_values
        )
    except Exception as audit_error:
        logger.error(f"❌ [AUDIT] Error al registrar eliminación de usuario {user_id_for_audit}: {audit_error}")

    return None
